language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t mazarag2/ui-frontend -f Dockerfile.dev .
script:
  - docker run -e CI=true mazarag2/ui-frontend npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react-ui"
  env: "Dockerreactui-env"
  bucket_name: "elasticbeanstalk-us-west-1-113021065873"
  bucket_path: "docker-react-ui"
  on:
    branch: master
  access_key_id: "$access_key_id"
  secret_access_key:
    secure: "$secret_access_key"
